name: smart_menu_app
description: SmartMenu V1.0 Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1

  # Database
  drift: ^2.34.3
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.6
  path: ^1.9.1

  # Models
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  equatable: ^2.0.7

  # Numeric calculation
  decimal: ^3.2.6

  # Navigation
  go_router: ^17.5.0

  # Local storage
  shared_preferences: ^2.5.5

  # Utilities
  logger: ^2.7.0
  uuid: ^4.6.0
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.16.0
  drift_dev: ^2.34.5
  freezed: ^4.0.0-dev.3
  json_serializable: ^6.14.1

  # Testing
  mockito: ^5.8.1
  mocktail: ^1.0.5

  # Lints
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

hooks:
  user_defines:
    sqlite3:
      source: source
      path: third_party/sqlite/sqlite-amalgamation-3500200/sqlite3.c
